- type: job
  id: STMagistrate
  name: stories-job-name-magistrate
  description: stories-job-description-magistrate
  playTimeTracker: STJobMagistrate
  setPreference: false
  startingGear: STMagistrateGear
  icon: "STJobIconMagistrate"
  supervisors: stories-job-supervisors-management-juridical-department
  accessGroups:
  - AllAccess
  - STPrisonAllAccess # Stories
  access:
  - CentralCommand
  - STDSO
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, STDeathRattleImplantDSO, RadioImplantCentcomm, STRadioImplantDSO ]

- type: startingGear
  id: STMagistrateGear
  equipment:
    head: STClothingHeadHatMagistrate
    jumpsuit: STClothingUniformJumpsuitProsecutorBlack
    back: ClothingBackpackSatchelHolding
    eyes: STClothingEyesGlassesCentcom
    ears: ClothingHeadsetAltCentCom
    gloves: ClothingHandsGlovesHop
    shoes: ClothingShoesBootsLaceup
    id: STMagistratePDA
    outerClothing: STClothingOuterRobesMagistrate
    neck: STClothingNeckCloakMagistrate
    pocket1: ToyHammer
    pocket2: STRubberStampMagistrate
    belt: BoxFolderCentComClipboardThreePapers
  storage:
    back:
    - BoxSurvival
