- type: job
  id: STSpecialOfficer
  name: stories-job-name-special-officer
  description: stories-job-description-special-officer
  playTimeTracker: STJobSpecialOfficer
  setPreference: false
  startingGear: STSpecialOfficerGear
  icon: "STJobIconSpecialOfficer"
  supervisors: stories-job-supervisors-admiralty
  accessGroups:
  - AllAccess
  - STPrisonAllAccess # Stories
  access:
  - CentralCommand
  - STDSO
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, STDeathRattleImplantDSO, RadioImplantCentcomm, STRadioImplantDSO ]

- type: startingGear
  id: STSpecialOfficerGear
  equipment:
    head: STClothingHeadHatBeretSpecialOfficer
    jumpsuit: STClothingUniformJumpsuitSpecialOfficer
    back: ClothingBackpackSatchelHolding
    mask: ClothingMaskNeckGaiter
    eyes: STClothingEyesGlassesCentcom
    ears: ClothingHeadsetAltCentCom
    gloves: ClothingHandsGlovesCombat
    shoes: STClothingShoesBootsJackGuardianNt
    id: STSpecialOfficerPDA
    outerClothing: ClothingOuterVestWeb
    neck: STClothingNeckCloakSpecialOfficer
    pocket1: WeaponDisabler
    pocket2: STRubberStampSpecialOfficer
    belt: ClothingBeltSecurityFilled
  storage:
    back:
    - BoxSurvivalSecurity
