- type: job
  id: STEngineerCentcom
  name: stories-job-name-engineer-centcom
  description: stories-job-description-engineer-centcom
  playTimeTracker: STJobEngineerCentcom
  setPreference: false
  startingGear: STEngineerCentcomGear
  icon: "STJobIconEngineerCentcom"
  supervisors: job-supervisors-centcom
  access:
  - Atmospherics
  - Engineering
  - External
  - Maintenance
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, RadioImplantCentcomm ]

- type: startingGear
  id: STEngineerCentcomGear
  equipment:
    head: ClothingHeadHatBeretEngineering
    jumpsuit: STClothingUniformJumpsuitEngineerCentcom
    back: ClothingBackpackSatchelEngineering
    eyes: ClothingEyesGlassesMeson
    ears: ClothingHeadsetEngineering
    gloves: ClothingHandsGlovesColorYellow
    shoes: ClothingShoesColorWhite
    id: STEngineerCentcomPDA
    neck: ClothingNeckEngineermedal
    belt: ClothingBeltUtilityEngineering
  storage:
    back:
    - BoxSurvivalEngineering
