- type: job
  id: STOperatorCentcom
  name: stories-job-name-operator-centcom
  description: stories-job-description-operator-centcom
  playTimeTracker: STJobOperatorCentcom
  setPreference: false
  startingGear: STChiefCentcomGear
  icon: "STJobIconCentcom"
  supervisors: stories-job-supervisors-chief-centcom
  accessGroups:
  - AllAccess
  - STPrisonAllAccess # Stories
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm, RadioImplantCentcomm ]

- type: startingGear
  id: STOperatorCentcomGear
  equipment:
    head: ClothingHeadHatCentcom
    jumpsuit: ClothingUniformJumpsuitCentcomOfficial
    back: ClothingBackpackSatchelLeather
    eyes: STClothingEyesGlassesCentcom
    ears: ClothingHeadsetAltCentCom
    gloves: ClothingHandsGlovesCombat
    shoes: ClothingShoesBootsLaceup
    id: STOperatorCentcomPDA
    outerClothing: ClothingOuterArmorCentcommCarapace
    neck: STClothingNeckCloakOperatorCentcom
    belt: BoxFolderCentComClipboard
  storage:
    back:
    - BoxSurvival
