# Prison-Jobs

- type: playTimeTracker
  id: STJobPrisoner

- type: playTimeTracker
  id: STJobHeadOfSpacePrison

- type: playTimeTracker
  id: STJobSpacePrisonOfficer

- type: playTimeTracker
  id: STJobSpacePrisonEngineer

- type: playTimeTracker
  id: STJobSpacePrisonMedic

- type: playTimeTracker
  id: STJobIAA

- type: playTimeTracker
  id: STJobGuardianNt

- type: playTimeTracker
  id: JobSTPartyMaker

# Centcom-Jobs

- type: playTimeTracker
  id: JobSTChiefCentcom

- type: playTimeTracker
  id: JobSTOperatorCentcom

- type: playTimeTracker
  id: JobSTRepresentativeCentcom

- type: playTimeTracker
  id: JobSTHeadOfSecurityCentcom

- type: playTimeTracker
  id: JobGuardianNt

- type: playTimeTracker
  id: JobSTSecurityOfficerCentcom

- type: playTimeTracker
  id: JobSTMedicCentcom

- type: playTimeTracker
  id: JobSTEngineerCentcom

- type: playTimeTracker
  id: JobSTWorkerCentcom

# Juridical-Jobs

- type: playTimeTracker
  id: JobSTMagistrate

- type: playTimeTracker
  id: JobIAA

- type: playTimeTracker
  id: STJobJudge

- type: playTimeTracker
  id: STJobSecurityClown

- type: playTimeTracker
  id: STJobSpecialOfficer

- type: playTimeTracker
  id: STJobCommandMaid

- type: playTimeTracker
  id: STJobPartyMaker

- type: playTimeTracker
  id: STJobBlueshield
