# Prison-Jobs

- type: playTimeTracker
  id: STJobPrisoner

- type: playTimeTracker
  id: STJobHeadOfSpacePrison

- type: playTimeTracker
  id: STJobSpacePrisonOfficer

- type: playTimeTracker
  id: STJobSpacePrisonEngineer

- type: playTimeTracker
  id: STJobSpacePrisonMedic

- type: playTimeTracker
  id: STJobIAA

- type: playTimeTracker
  id: STJobGuardianNt

- type: playTimeTracker
  id: STJobBrigmedic

- type: playTimeTracker
  id: STJobJudge

- type: playTimeTracker
  id: STJobSecurityClown

- type: playTimeTracker
  id: STJobSpecialOfficer

- type: playTimeTracker
  id: STJobCommandMaid

- type: playTimeTracker
  id: STJobPartyMaker

- type: playTimeTracker
  id: STJobBlueshield

- type: playTimeTracker
  id: STJobChiefCentcom

- type: playTimeTracker
  id: STJobOperatorCentcom

- type: playTimeTracker
  id: STJobRepresentativeCentcom

- type: playTimeTracker
  id: STJobHeadOfSecurityCentcom

- type: playTimeTracker
  id: JobGuardianNt

- type: playTimeTracker
  id: STJobSecurityOfficerCentcom

- type: playTimeTracker
  id: STJobMedicCentcom

- type: playTimeTracker
  id: STJobEngineerCentcom

- type: playTimeTracker
  id: STJobWorkerCentcom

- type: playTimeTracker
  id: STJobMagistrate
